[package]
name = "nmsl-telegram-bot-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nmsl-telegram-bot"
path = "./src/main.rs"

[lib]
name = "nmsl_core"
path = "./src/lib.rs"

[dependencies]
teloxide = { version = "0.5", features = ["auto-send", "macros"] }
teloxide-listener = { git = "https://github.com/PhotonQuantum/teloxide-listener", features = ["webhook"] }
jieba-rs = "0.6"
serde = "1.0"
serde_json = "1.0"
pinyin = "0.8"
itertools = "0.10"
log = "0.4"
pretty_env_logger = "0.4"
indexmap = { version = "1.7", features=["serde-1"] }
tokio-stream = "0.1"
md5 = "0.7"
tokio = { version = "1.14", features=["full"] }